---
course_pace_draft_state:
  state: hidden
  applies_to: RootAccount
  display_name: Course Pace Drafts
  description: Allows for creating course paces in a draft/unpublished state, and allows for updating a pace draft unlimited times before publishing